version: "2"

services:
  mysql:
    build: .
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
    driver: local
